### ISSUE TITLE
[Feature Request] Add option for single-quotes instead of double-quotes

### ISSUE THREAD

**Issue by TrevorSayre** [gottfired/css2react#3]
Our linting setup requires single-quotes in the places where css2react is most useful. It would be nice to have a preference to convert using single-quotes instead of double-quotes.

```
// User Settings
{
  "css2react.quotes": "single", // defaults to "double"
}
```

**Comment by gottfired** [comment]
Hi, One year later it's done :)
The setting is called "css2react.singleQuotes" which defaults to false
