### ISSUE TITLE
command 'extension.css2react' not found

### ISSUE THREAD

**Issue by Graham42** [gottfired/css2react#4]
I keep getting the error 
> command 'extension.css2react' not found

Not sure what's wrong :cry:

**Comment by gottfired** [comment]
Is that only since the update or is this a fresh install?

**Comment by Graham42** [comment]
I'm not sure, I ended up uninstalling this extension and installing [CSS to JSS](https://marketplace.visualstudio.com/items?itemName=infarkt.css-to-jss) instead.

**Comment by mifas** [comment]
Happening to me as well.

**Comment by gottfired** [comment]
What version of vscode are you using?

**Comment by mifas** [comment]
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-32-generic
```

I also tried with a fresh install. Cleared vscode config and removed all extensions

**Comment by gottfired** [comment]
I’ll have a look at it. But I can’t promise anything. I‘m on a Mac or windows PC and it works on both platforms.

**Comment by gottfired** [comment]
Should be fixed now. Sorry for the delay. Corona quarantine gave me time to look at the issue.
